server:
  port: 8085

spring:
  mail:
         host: smtp.163.com
         username: sendBaBa@163.com #邮箱地址
         password: send105 #授权密码（非email密码sendBaBa105）
         default-encoding: UTF-8
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/medical?useUnicode=true&amp;characterEncoding=utf-8
      username: root
      password: aptech
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: cn.kgc.demo4.servie.*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置
      stat-view-servlet:
          enabled: true
          # 访问路径为/druid时，跳转到StatViewServlet
          url-pattern: /druid/*
          # 是否能够重置数据
          reset-enable: false
          # 需要账号密码才能访问控制台
          login-username: druid
          login-password: druid123
      # 配置StatFilter
      filter:
         stat:
          log-slow-sql: true
  cache:
      type: redis
  redis:
      # Redis服务器地址
      host: 127.0.0.1
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器连接端口
      port: 6379
      password: aptech
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      timeout: 0
logging:
  level:
   cn:
     ling:
      medical2:
       mapper: debug
mybatis:
  # 扫描的实体类 取别名
  type-aliases-package: cn.ling.medical.pojo
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
